"""Add extension field to Memes model

Revision ID: ff56ad57778b
Revises: 04d904f09eeb
Create Date: 2024-07-03 20:42:26.971459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff56ad57778b'
down_revision: Union[str, None] = '04d904f09eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('extension', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'extension')
    # ### end Alembic commands ###
