"""Memes model fix

Revision ID: b157a786fcee
Revises: beb7f0227eea
Create Date: 2024-07-02 14:21:36.718947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b157a786fcee'
down_revision: Union[str, None] = 'beb7f0227eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('memes_name_key', 'memes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('memes_name_key', 'memes', ['name'])
    # ### end Alembic commands ###
