"""Memes model disable dbms side id generate

Revision ID: 04d904f09eeb
Revises: b157a786fcee
Create Date: 2024-07-03 12:04:15.786945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d904f09eeb'
down_revision: Union[str, None] = 'b157a786fcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'memes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memes', type_='unique')
    # ### end Alembic commands ###
