"""Memes model add media_type.

Revision ID: 7072d0a0fcc7
Revises: 2dda52148012
Create Date: 2024-07-20 18:45:43.135965

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7072d0a0fcc7'
down_revision: Union[str, None] = '2dda52148012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('media_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'media_type')
    # ### end Alembic commands ###
